# Generated by Django 3.2.7 on 2021-09-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Discounted_price',
            new_name='discounted_price',
        ),
    ]
