# Generated by Django 3.2.7 on 2021-09-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_discounted_price_product_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shoes', 'shoes'), ('food', 'food'), ('clothes', 'clothes')], default='selcect a category', max_length=40)),
            ],
        ),
    ]
