# Generated by Django 3.2.7 on 2021-10-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20211019_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('clothes', 'clothes'), ('food', 'food'), ('shoes', 'shoes')], default='selcect a category', max_length=40),
        ),
    ]
