# Generated by Django 3.2.7 on 2021-10-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_categories_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='User.first_name', max_length=200)),
                ('last_name', models.CharField(default='User.last_name', max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('picture', models.ImageField(upload_to='profile_pics')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('username', models.CharField(default='User.username', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('clothes', 'clothes'), ('shoes', 'shoes'), ('food', 'food')], default='selcect a category', max_length=40),
        ),
    ]
