# Generated by Django 3.2.7 on 2021-10-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20211004_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('clothes', 'clothes'), ('food', 'food'), ('shoes', 'shoes')], default='selcect a category', max_length=40),
        ),
    ]
