# Generated by Django 3.2.7 on 2021-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20211017_0510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrandTotal',
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('food', 'food'), ('clothes', 'clothes'), ('shoes', 'shoes')], default='selcect a category', max_length=40),
        ),
    ]
